"""wtf

Revision ID: 1f8339c84df6
Revises: 692df5172f30
Create Date: 2025-03-08 00:17:32.693107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f8339c84df6'
down_revision: Union[str, None] = '692df5172f30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeframe', sa.Column('datetime_interval', sa.Interval(), nullable=False))
    op.drop_column('timeframe', 'detetime_interval')
    op.alter_column('tradepair', 'tracking',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tradepair', 'delisted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tradepair', 'delisted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('tradepair', 'tracking',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.add_column('timeframe', sa.Column('detetime_interval', postgresql.INTERVAL(), autoincrement=False, nullable=False))
    op.drop_column('timeframe', 'datetime_interval')
    # ### end Alembic commands ###
