"""Tradepair boolean columns default values fix

Revision ID: 53b445860da0
Revises: fdb0cba21e1b
Create Date: 2025-03-06 17:38:59.218843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53b445860da0'
down_revision: Union[str, None] = 'fdb0cba21e1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
