"""Reinit

Revision ID: 692df5172f30
Revises: 
Create Date: 2025-03-08 00:07:52.744621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '692df5172f30'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeframe',
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('detetime_interval', sa.Interval(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('tradepair',
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('tracking', sa.Boolean(), nullable=False),
    sa.Column('delisted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('candle',
    sa.Column('tradepair_name', sa.String(length=20), nullable=False),
    sa.Column('timeframe_name', sa.String(length=10), nullable=False),
    sa.Column('datetime_open', sa.DateTime(), nullable=False),
    sa.Column('datetime_close', sa.DateTime(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['timeframe_name'], ['timeframe.name'], ),
    sa.ForeignKeyConstraint(['tradepair_name'], ['tradepair.name'], ),
    sa.PrimaryKeyConstraint('tradepair_name', 'timeframe_name', 'datetime_open')
    )
    op.create_table('swing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tradepair_name', sa.String(length=20), nullable=False),
    sa.Column('timeframe_name', sa.String(length=10), nullable=False),
    sa.Column('orientation_up', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['timeframe_name'], ['timeframe.name'], ),
    sa.ForeignKeyConstraint(['tradepair_name'], ['tradepair.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('swing_candle_link',
    sa.Column('swing_id', sa.Integer(), nullable=False),
    sa.Column('candle_tradepair', sa.String(length=20), nullable=False),
    sa.Column('candle_timeframe', sa.String(length=10), nullable=False),
    sa.Column('candle_datetime_open', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candle_tradepair', 'candle_timeframe', 'candle_datetime_open'], ['candle.tradepair_name', 'candle.timeframe_name', 'candle.datetime_open'], ),
    sa.ForeignKeyConstraint(['swing_id'], ['swing.id'], ),
    sa.PrimaryKeyConstraint('swing_id', 'candle_tradepair', 'candle_timeframe', 'candle_datetime_open')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('swing_candle_link')
    op.drop_table('swing')
    op.drop_table('candle')
    op.drop_table('tradepair')
    op.drop_table('timeframe')
    # ### end Alembic commands ###
