"""Initial migration

Revision ID: 831524c0d729
Revises: 
Create Date: 2025-03-01 18:37:33.104088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '831524c0d729'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeframe',
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('type')
    )
    op.create_table('tradepair',
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('tracking', sa.Boolean(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('candle',
    sa.Column('tradepair_name', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('datetime_open', sa.DateTime(), nullable=False),
    sa.Column('datetime_close', sa.DateTime(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['timeframe'], ['timeframe.type'], ),
    sa.ForeignKeyConstraint(['tradepair_name'], ['tradepair.name'], ),
    sa.PrimaryKeyConstraint('tradepair_name', 'timeframe', 'datetime_open')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candle')
    op.drop_table('tradepair')
    op.drop_table('timeframe')
    # ### end Alembic commands ###
